FROM microsoft/aspnetcore-build:2-jessie AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln ./
COPY SimpleNetCoreApi/SimpleNetCoreApi.csproj SimpleNetCoreApi/
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o /app

# build runtime image
FROM microsoft/aspnetcore:2-jessie
WORKDIR /app

COPY --from=build-env /app ./
ENTRYPOINT ["dotnet", "SimpleNetCoreApi.dll"]
